apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-operator
  labels:
    app: chaos-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaos-operator
  template:
    metadata:
      labels:
        app: chaos-operator
    spec:
      serviceAccountName: chaos-operator
      containers:
      - name: chaos-operator
        image: chaos-engineering-as-a-platform/chaos-operator:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: chaos-platform-env
        volumeMounts:
        - name: kubeconfig
          mountPath: /app/kubeconfig.yaml
          subPath: kubeconfig.yaml
      volumes:
      - name: kubeconfig
        configMap:
          name: chaos-operator-kubeconfig
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaos-operator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-operator
subjects:
- kind: ServiceAccount
  name: chaos-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: chaos-operator
  apiGroup: rbac.authorization.k8s.io