apiVersion: v1
kind: Secret
metadata:
  name: chaos-platform-env
type: Opaque
data:
  # These values should be base64 encoded in a real deployment
  # Example: echo -n "value" | base64
  DB_USER: cG9zdGdyZXM=  # postgres
  DB_PASSWORD: cG9zdGdyZXM=  # postgres
  DB_HOST: cG9zdGdyZXM=  # postgres
  DB_PORT: NTQzMg==  # 5432
  DB_NAME: Y2hhb3NfcGxhdGZvcm0=  # chaos_platform
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpwYXNzd29yZEBwb3N0Z3Jlczo1NDMyL2NoYW9zX3BsYXRmb3JtP3NzbG1vZGU9ZGlzYWJsZQ==
  KUBE_TOKEN: ZHVtbXktdG9rZW4=  # dummy-token
  GF_SECURITY_ADMIN_PASSWORD: YWRtaW4=  # admin