global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'chaos-api-server'
    static_configs:
      - targets: ['api-server:8080']

  - job_name: 'chaos-operator'
    static_configs:
      - targets: ['chaos-operator:8080']