apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api-server
  labels:
    app: {{ .Release.Name }}-api-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api-server
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api-server
    spec:
      containers:
        - name: api-server
          image: "{{ .Values.image.repository }}-api-server:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.apiServer.port }}
              protocol: TCP
          env:
            - name: PORT
              value: "{{ .Values.apiServer.port }}"
            - name: ENVIRONMENT
              value: "production"
            {{- if .Values.postgresql.enabled }}
            - name: DB_HOST
              value: "{{ .Release.Name }}-postgresql"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "{{ .Values.postgresql.auth.database }}"
            - name: DB_USER
              value: "{{ .Values.postgresql.auth.username }}"
            - name: DB_PASSWORD
              value: "{{ .Values.postgresql.auth.password }}"
            {{- else }}
            - name: DB_HOST
              value: "{{ .Values.database.host }}"
            - name: DB_PORT
              value: "{{ .Values.database.port }}"
            - name: DB_NAME
              value: "{{ .Values.database.name }}"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret }}
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret }}
                  key: password
            {{- end }}
            - name: PROMETHEUS_ENABLED
              value: "{{ .Values.monitoring.prometheus.enabled }}"
          resources:
            {{- toYaml .Values.apiServer.resources | nindent 12 }}