apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-server
  labels:
    app: {{ .Release.Name }}-api-server
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.apiServer.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-api-server