apiVersion: v1
kind: Config
clusters:
- name: default
  cluster:
    server: https://kubernetes.default.svc
    certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
users:
- name: default
  user:
    token: dummy-token-for-development
contexts:
- name: default
  context:
    cluster: default
    user: default
    namespace: default
current-context: default