apiVersion: v2
name: chaos-platform
description: A Helm chart for Chaos Engineering as a Platform
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: "~12.5.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: prometheus
    version: "~19.6.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  - name: grafana
    version: "~6.52.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled